### ISSUE TITLE
Can it support servers that doesn't talk head request?

### ISSUE THREAD

**Issue by nripendra** [zenflow/node-fast-download#6]
Hi,

I'm trying to use this in one of my projects but having problem with the head request. Can it support without having to call head request at all?

**Comment by zenflow** [comment]
Heya,

There is no support for skipping the HEAD request at this time.

If the http server won't handle HEAD requests, then it seems unlikely that it will handle the range headers (i.e. `range: bytes=1000-2000`) included in all the GET requests, necessary for requesting different chunks.

What kind of http server are you trying to download from?

**Comment by nripendra** [comment]
It is Amazon s3 download url

**Comment by zenflow** [comment]
@nripendra sorry for such the delay.. I hope you are still mildly interested in this issue..

> To be more precise it is github's download url for downloading release asset.

Do you mean a URL like this? https://github.com/zenflow/node-fast-download/archive/v0.3.5.zip

I checked it out with `curl --insecure --head --verbose https://github.com/zenflow/node-fast-download/archive/v0.3.5.zip` and it seems like it **does** talk head request. 

Please give me another URL example if I misunderstood. Or maybe this server has changed since the issue was opened.

One thing I noticed in the HEAD response is that it doesn't have any [Accept-Ranges header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges) to "advertise its support of partial request". Servers that don't support partial request will not work with this module or any similar download accelerators.

**Comment by nripendra** [comment]
@zenflow 

Sorry but I'm no longer actively working on this project. But it could be true that things may have changed during these times.
